apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama2-7b-pv
  labels:
    type: local
spec:
  storageClassName: llama2-7b-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
