apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: llama2-7b-sc
provisioner: kubernetes.io/no-provisioner
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer
